<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_597627a4a2621',
		'title' => 'Slaideri sätted',
		'fields' => array(
			array(
				'key' => 'field_597627ae4efca',
				'label' => 'Slaidi vahetamise kiirus',
				'name' => 'slaidi_vahetamise_kiirus',
				'type' => 'number',
				'instructions' => 'Millisekundites nt 8000',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => 8000,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => 1000,
			),
			array(
				'key' => 'field_597627e4845aa',
				'label' => 'Luba slaidivahetuse nupud',
				'name' => 'luba_slaidivahetus_nupud',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'Jah',
				'ui_off_text' => 'Ei',
			),
			array(
				'key' => 'field_59762860845ab',
				'label' => 'Luba slaidivahetuse nooled',
				'name' => 'luba_slaidivahetus_nooled',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'Jah',
				'ui_off_text' => 'Ei',
			),
			array(
				'key' => 'field_597628a6845ac',
				'label' => 'Slaideri kõrgus',
				'name' => 'slaideri_korgus',
				'type' => 'number',
				'instructions' => 'Protsentides',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => 30,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_597a4ea77f8ce',
				'label' => 'Teksti ala laius',
				'name' => 'teksti_ala_laius',
				'type' => 'number',
				'instructions' => 'Ala, mis ümbritseb nagu "wrapper" teksti paremat ja vasakut äärt pikslites',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5ba3a2b77b0f1',
				'label' => 'Taustapilt',
				'name' => 'taustapilt',
				'type' => 'image',
				'instructions' => 'Kui panna taustapilt siia siis ei pea slaididel taustapilte panema.	Ainult teksti.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-slaideri-satted',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;
?>